# Generated by Django 5.1.2 on 2024-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('creationDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
    ]
